// <auto-generated>This is auto-generated code by DIS. Do not modify.</auto-generated>
using System.ComponentModel;
using System.Collections;
using System.Collections.Generic;
using System.Linq;

namespace Skyline.DataMiner.Scripting
{
public static class Parameter
{
	/// <summary>PID: 4 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int encoderstatus_4 = 4;
	/// <summary>PID: 4 | Type: read</summary>
	public const int encoderstatus = 4;
	/// <summary>PID: 5 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int decoderstatus_5 = 5;
	/// <summary>PID: 5 | Type: read</summary>
	public const int decoderstatus = 5;
	/// <summary>PID: 6 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int encodercurrentcompressedbitrate_6 = 6;
	/// <summary>PID: 6 | Type: read</summary>
	public const int encodercurrentcompressedbitrate = 6;
	/// <summary>PID: 7 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int decodercurrentcompressedbitrate_7 = 7;
	/// <summary>PID: 7 | Type: read</summary>
	public const int decodercurrentcompressedbitrate = 7;
	/// <summary>PID: 8 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int encoderautochromaweight_8 = 8;
	/// <summary>PID: 8 | Type: read</summary>
	public const int encoderautochromaweight = 8;
	/// <summary>PID: 10 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int encoderlosslessmode_10 = 10;
	/// <summary>PID: 10 | Type: read</summary>
	public const int encoderlosslessmode = 10;
	/// <summary>PID: 11 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int decoderprogressionorder_11 = 11;
	/// <summary>PID: 11 | Type: read</summary>
	public const int decoderprogressionorder = 11;
	/// <summary>PID: 12 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int decodercodeblockwidth_12 = 12;
	/// <summary>PID: 12 | Type: read</summary>
	public const int decodercodeblockwidth = 12;
	/// <summary>PID: 13 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int decodercodeblockheight_13 = 13;
	/// <summary>PID: 13 | Type: read</summary>
	public const int decodercodeblockheight = 13;
	/// <summary>PID: 17 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int encoderchromaweight_17 = 17;
	/// <summary>PID: 17 | Type: read</summary>
	public const int encoderchromaweight = 17;
	/// <summary>PID: 106 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int copyofencodercurrentcompressedbitrate_106 = 106;
	/// <summary>PID: 106 | Type: read</summary>
	public const int copyofencodercurrentcompressedbitrate = 106;
	/// <summary>PID: 107 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int copyofdecodercurrentcompressedbitrate_107 = 107;
	/// <summary>PID: 107 | Type: read</summary>
	public const int copyofdecodercurrentcompressedbitrate = 107;
	/// <summary>PID: 108 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int copyofencoderautochromaweight_108 = 108;
	/// <summary>PID: 108 | Type: read</summary>
	public const int copyofencoderautochromaweight = 108;
	/// <summary>PID: 110 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int copyofencoderlosslessmode_110 = 110;
	/// <summary>PID: 110 | Type: read</summary>
	public const int copyofencoderlosslessmode = 110;
	/// <summary>PID: 111 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int copyofdecoderprogressionorder_111 = 111;
	/// <summary>PID: 111 | Type: read</summary>
	public const int copyofdecoderprogressionorder = 111;
	/// <summary>PID: 112 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int copyofdecodercodeblockwidth_112 = 112;
	/// <summary>PID: 112 | Type: read</summary>
	public const int copyofdecodercodeblockwidth = 112;
	/// <summary>PID: 113 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int copyofdecodercodeblockheight_113 = 113;
	/// <summary>PID: 113 | Type: read</summary>
	public const int copyofdecodercodeblockheight = 113;
	/// <summary>PID: 117 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int copyofencoderchromaweight_117 = 117;
	/// <summary>PID: 117 | Type: read</summary>
	public const int copyofencoderchromaweight = 117;
	public class Write
	{
		/// <summary>PID: 54 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int encoderstatus_54 = 54;
		/// <summary>PID: 54 | Type: write</summary>
		public const int encoderstatus = 54;
		/// <summary>PID: 55 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int decoderstatus_55 = 55;
		/// <summary>PID: 55 | Type: write</summary>
		public const int decoderstatus = 55;
		/// <summary>PID: 58 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int encoderautochromaweight_58 = 58;
		/// <summary>PID: 58 | Type: write</summary>
		public const int encoderautochromaweight = 58;
		/// <summary>PID: 60 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int encoderlosslessmode_60 = 60;
		/// <summary>PID: 60 | Type: write</summary>
		public const int encoderlosslessmode = 60;
		/// <summary>PID: 61 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int decoderprogressionorder_61 = 61;
		/// <summary>PID: 61 | Type: write</summary>
		public const int decoderprogressionorder = 61;
		/// <summary>PID: 67 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int encoderchromaweight_67 = 67;
		/// <summary>PID: 67 | Type: write</summary>
		public const int encoderchromaweight = 67;
	}
}
public class WriteParameters
{
	/// <summary>PID: 54  | Type: write | DISCREETS: Disabled = 0, Enabled = 1</summary>
	public System.Object Encoderstatus {get { return Protocol.GetParameter(54); }set { Protocol.SetParameter(54, value); }}
	/// <summary>PID: 55  | Type: write | DISCREETS: Disabled = 0, Enabled = 1</summary>
	public System.Object Decoderstatus {get { return Protocol.GetParameter(55); }set { Protocol.SetParameter(55, value); }}
	/// <summary>PID: 58  | Type: write | DISCREETS: Disabled = 0, Enabled = 1</summary>
	public System.Object Encoderautochromaweight {get { return Protocol.GetParameter(58); }set { Protocol.SetParameter(58, value); }}
	/// <summary>PID: 60  | Type: write | DISCREETS: Disabled = 0, Enabled = 1</summary>
	public System.Object Encoderlosslessmode {get { return Protocol.GetParameter(60); }set { Protocol.SetParameter(60, value); }}
	/// <summary>PID: 61  | Type: write | DISCREETS: LCRP = 0, RLCP = 1, RPCL = 2, PCRL = 3, CPRL = 4</summary>
	public System.Object Decoderprogressionorder {get { return Protocol.GetParameter(61); }set { Protocol.SetParameter(61, value); }}
	/// <summary>PID: 67  | Type: write</summary>
	public System.Object Encoderchromaweight {get { return Protocol.GetParameter(67); }set { Protocol.SetParameter(67, value); }}
	public SLProtocolExt Protocol;
	public WriteParameters(SLProtocolExt protocol)
	{
		Protocol = protocol;
	}
}
public interface SLProtocolExt : SLProtocol
{
	object Title_begin_encoder__fixed { get; set; }
	object Afterstartup_dummy { get; set; }
	object Title_begin_decoder__fixed { get; set; }
	object Encoderstatus_4 { get; set; }
	object Encoderstatus { get; set; }
	object Decoderstatus_5 { get; set; }
	object Decoderstatus { get; set; }
	object Encodercurrentcompressedbitrate_6 { get; set; }
	object Encodercurrentcompressedbitrate { get; set; }
	object Decodercurrentcompressedbitrate_7 { get; set; }
	object Decodercurrentcompressedbitrate { get; set; }
	object Encoderautochromaweight_8 { get; set; }
	object Encoderautochromaweight { get; set; }
	object Encoderlosslessmode_10 { get; set; }
	object Encoderlosslessmode { get; set; }
	object Decoderprogressionorder_11 { get; set; }
	object Decoderprogressionorder { get; set; }
	object Decodercodeblockwidth_12 { get; set; }
	object Decodercodeblockwidth { get; set; }
	object Decodercodeblockheight_13 { get; set; }
	object Decodercodeblockheight { get; set; }
	object Notavailable__fixed { get; set; }
	object Setstatustodisabled__fixed { get; set; }
	object Encoderchromaweight_17 { get; set; }
	object Encoderchromaweight { get; set; }
	object Encoderstatus_54 { get; set; }
	object Decoderstatus_55 { get; set; }
	object Encoderautochromaweight_58 { get; set; }
	object Encoderlosslessmode_60 { get; set; }
	object Decoderprogressionorder_61 { get; set; }
	object Encoderchromaweight_67 { get; set; }
	object Copyofencodercurrentcompressedbitrate_106 { get; set; }
	object Copyofencodercurrentcompressedbitrate { get; set; }
	object Copyofdecodercurrentcompressedbitrate_107 { get; set; }
	object Copyofdecodercurrentcompressedbitrate { get; set; }
	object Copyofencoderautochromaweight_108 { get; set; }
	object Copyofencoderautochromaweight { get; set; }
	object Copyofencoderlosslessmode_110 { get; set; }
	object Copyofencoderlosslessmode { get; set; }
	object Copyofdecoderprogressionorder_111 { get; set; }
	object Copyofdecoderprogressionorder { get; set; }
	object Copyofdecodercodeblockwidth_112 { get; set; }
	object Copyofdecodercodeblockwidth { get; set; }
	object Copyofdecodercodeblockheight_113 { get; set; }
	object Copyofdecodercodeblockheight { get; set; }
	object Copyofencoderchromaweight_117 { get; set; }
	object Copyofencoderchromaweight { get; set; }
	WriteParameters Write { get; set; }
}
public class ConcreteSLProtocolExt : ConcreteSLProtocol, SLProtocolExt
{
	/// <summary>PID: 1  | Type: fixed</summary>
	public System.Object Title_begin_encoder__fixed {get { return GetParameter(1); }set { SetParameter(1, value); }}
	/// <summary>PID: 2  | Type: dummy</summary>
	public System.Object Afterstartup_dummy {get { return GetParameter(2); }set { SetParameter(2, value); }}
	/// <summary>PID: 3  | Type: fixed</summary>
	public System.Object Title_begin_decoder__fixed {get { return GetParameter(3); }set { SetParameter(3, value); }}
	/// <summary>PID: 4  | Type: read | DISCREETS: Disabled = 0, Enabled = 1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Encoderstatus_4 {get { return GetParameter(4); }set { SetParameter(4, value); }}
	/// <summary>PID: 4  | Type: read | DISCREETS: Disabled = 0, Enabled = 1</summary>
	public System.Object Encoderstatus {get { return GetParameter(4); }set { SetParameter(4, value); }}
	/// <summary>PID: 5  | Type: read | DISCREETS: Disabled = 0, Enabled = 1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Decoderstatus_5 {get { return GetParameter(5); }set { SetParameter(5, value); }}
	/// <summary>PID: 5  | Type: read | DISCREETS: Disabled = 0, Enabled = 1</summary>
	public System.Object Decoderstatus {get { return GetParameter(5); }set { SetParameter(5, value); }}
	/// <summary>PID: 6  | Type: read | EXCEPTIONS: Not Available = -1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Encodercurrentcompressedbitrate_6 {get { return GetParameter(6); }set { SetParameter(6, value); }}
	/// <summary>PID: 6  | Type: read | EXCEPTIONS: Not Available = -1</summary>
	public System.Object Encodercurrentcompressedbitrate {get { return GetParameter(6); }set { SetParameter(6, value); }}
	/// <summary>PID: 7  | Type: read | EXCEPTIONS: Not Available = -1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Decodercurrentcompressedbitrate_7 {get { return GetParameter(7); }set { SetParameter(7, value); }}
	/// <summary>PID: 7  | Type: read | EXCEPTIONS: Not Available = -1</summary>
	public System.Object Decodercurrentcompressedbitrate {get { return GetParameter(7); }set { SetParameter(7, value); }}
	/// <summary>PID: 8  | Type: read | DISCREETS: Disabled = 0, Enabled = 1 | EXCEPTIONS: Not Available = -1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Encoderautochromaweight_8 {get { return GetParameter(8); }set { SetParameter(8, value); }}
	/// <summary>PID: 8  | Type: read | DISCREETS: Disabled = 0, Enabled = 1 | EXCEPTIONS: Not Available = -1</summary>
	public System.Object Encoderautochromaweight {get { return GetParameter(8); }set { SetParameter(8, value); }}
	/// <summary>PID: 10  | Type: read | DISCREETS: Disabled = 0, Enabled = 1 | EXCEPTIONS: Not Available = -1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Encoderlosslessmode_10 {get { return GetParameter(10); }set { SetParameter(10, value); }}
	/// <summary>PID: 10  | Type: read | DISCREETS: Disabled = 0, Enabled = 1 | EXCEPTIONS: Not Available = -1</summary>
	public System.Object Encoderlosslessmode {get { return GetParameter(10); }set { SetParameter(10, value); }}
	/// <summary>PID: 11  | Type: read | DISCREETS: LCRP = 0, RLCP = 1, RPCL = 2, PCRL = 3, CPRL = 4 | EXCEPTIONS: Not Avilable = -1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Decoderprogressionorder_11 {get { return GetParameter(11); }set { SetParameter(11, value); }}
	/// <summary>PID: 11  | Type: read | DISCREETS: LCRP = 0, RLCP = 1, RPCL = 2, PCRL = 3, CPRL = 4 | EXCEPTIONS: Not Avilable = -1</summary>
	public System.Object Decoderprogressionorder {get { return GetParameter(11); }set { SetParameter(11, value); }}
	/// <summary>PID: 12  | Type: read | EXCEPTIONS: Not Avilable = -1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Decodercodeblockwidth_12 {get { return GetParameter(12); }set { SetParameter(12, value); }}
	/// <summary>PID: 12  | Type: read | EXCEPTIONS: Not Avilable = -1</summary>
	public System.Object Decodercodeblockwidth {get { return GetParameter(12); }set { SetParameter(12, value); }}
	/// <summary>PID: 13  | Type: read | EXCEPTIONS: Not Available = -1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Decodercodeblockheight_13 {get { return GetParameter(13); }set { SetParameter(13, value); }}
	/// <summary>PID: 13  | Type: read | EXCEPTIONS: Not Available = -1</summary>
	public System.Object Decodercodeblockheight {get { return GetParameter(13); }set { SetParameter(13, value); }}
	/// <summary>PID: 15  | Type: fixed</summary>
	public System.Object Notavailable__fixed {get { return GetParameter(15); }set { SetParameter(15, value); }}
	/// <summary>PID: 16  | Type: fixed</summary>
	public System.Object Setstatustodisabled__fixed {get { return GetParameter(16); }set { SetParameter(16, value); }}
	/// <summary>PID: 17  | Type: read | EXCEPTIONS: Not Available = -1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Encoderchromaweight_17 {get { return GetParameter(17); }set { SetParameter(17, value); }}
	/// <summary>PID: 17  | Type: read | EXCEPTIONS: Not Available = -1</summary>
	public System.Object Encoderchromaweight {get { return GetParameter(17); }set { SetParameter(17, value); }}
	/// <summary>PID: 54  | Type: write | DISCREETS: Disabled = 0, Enabled = 1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Encoderstatus_54 {get { return GetParameter(54); }set { SetParameter(54, value); }}
	/// <summary>PID: 55  | Type: write | DISCREETS: Disabled = 0, Enabled = 1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Decoderstatus_55 {get { return GetParameter(55); }set { SetParameter(55, value); }}
	/// <summary>PID: 58  | Type: write | DISCREETS: Disabled = 0, Enabled = 1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Encoderautochromaweight_58 {get { return GetParameter(58); }set { SetParameter(58, value); }}
	/// <summary>PID: 60  | Type: write | DISCREETS: Disabled = 0, Enabled = 1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Encoderlosslessmode_60 {get { return GetParameter(60); }set { SetParameter(60, value); }}
	/// <summary>PID: 61  | Type: write | DISCREETS: LCRP = 0, RLCP = 1, RPCL = 2, PCRL = 3, CPRL = 4</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Decoderprogressionorder_61 {get { return GetParameter(61); }set { SetParameter(61, value); }}
	/// <summary>PID: 67  | Type: write</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Encoderchromaweight_67 {get { return GetParameter(67); }set { SetParameter(67, value); }}
	/// <summary>PID: 106  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Copyofencodercurrentcompressedbitrate_106 {get { return GetParameter(106); }set { SetParameter(106, value); }}
	/// <summary>PID: 106  | Type: read</summary>
	public System.Object Copyofencodercurrentcompressedbitrate {get { return GetParameter(106); }set { SetParameter(106, value); }}
	/// <summary>PID: 107  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Copyofdecodercurrentcompressedbitrate_107 {get { return GetParameter(107); }set { SetParameter(107, value); }}
	/// <summary>PID: 107  | Type: read</summary>
	public System.Object Copyofdecodercurrentcompressedbitrate {get { return GetParameter(107); }set { SetParameter(107, value); }}
	/// <summary>PID: 108  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Copyofencoderautochromaweight_108 {get { return GetParameter(108); }set { SetParameter(108, value); }}
	/// <summary>PID: 108  | Type: read</summary>
	public System.Object Copyofencoderautochromaweight {get { return GetParameter(108); }set { SetParameter(108, value); }}
	/// <summary>PID: 110  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Copyofencoderlosslessmode_110 {get { return GetParameter(110); }set { SetParameter(110, value); }}
	/// <summary>PID: 110  | Type: read</summary>
	public System.Object Copyofencoderlosslessmode {get { return GetParameter(110); }set { SetParameter(110, value); }}
	/// <summary>PID: 111  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Copyofdecoderprogressionorder_111 {get { return GetParameter(111); }set { SetParameter(111, value); }}
	/// <summary>PID: 111  | Type: read</summary>
	public System.Object Copyofdecoderprogressionorder {get { return GetParameter(111); }set { SetParameter(111, value); }}
	/// <summary>PID: 112  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Copyofdecodercodeblockwidth_112 {get { return GetParameter(112); }set { SetParameter(112, value); }}
	/// <summary>PID: 112  | Type: read</summary>
	public System.Object Copyofdecodercodeblockwidth {get { return GetParameter(112); }set { SetParameter(112, value); }}
	/// <summary>PID: 113  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Copyofdecodercodeblockheight_113 {get { return GetParameter(113); }set { SetParameter(113, value); }}
	/// <summary>PID: 113  | Type: read</summary>
	public System.Object Copyofdecodercodeblockheight {get { return GetParameter(113); }set { SetParameter(113, value); }}
	/// <summary>PID: 117  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Copyofencoderchromaweight_117 {get { return GetParameter(117); }set { SetParameter(117, value); }}
	/// <summary>PID: 117  | Type: read</summary>
	public System.Object Copyofencoderchromaweight {get { return GetParameter(117); }set { SetParameter(117, value); }}
	public WriteParameters Write { get; set; }
	public ConcreteSLProtocolExt()
	{
		Write = new WriteParameters(this);
	}
}
}
